export default [
  "artliterature",
  "language",
  "sciencenature",
  "general",
  "fooddrink",
  "peopleplaces",
  "geography",
  "historyholidays",
  "entertainment",
  "toysgames",
  "music",
  "mathematics",
  "religionmythology",
  "sportsleisure",
  "random",
];
